# 🎮 Metaphor: ReFantazio Offline Setup Assistant Documentation

# Site settings
title: "Metaphor: ReFantazio Offline Setup Assistant"
description: "Ultimate offline setup and configuration assistant for Metaphor: ReFantazio. Play without internet, optimize settings, and enjoy the full JRPG experience locally."
baseurl: "/metaphor-refantazio-offline-setup-assistant"
url: "https://metaphor-refantazio-offline.github.io"

# Repository info
repository: "Metaphor-ReFantazio-Offline/metaphor-refantazio-offline-setup-assistant"
github_username: "Metaphor-ReFantazio-Offline"

# SEO settings
lang: en_US
author: "Metaphor: ReFantazio Offline Community"
twitter:
  username: MetaphorOffline
  card: summary_large_image
logo: "/assets/images/logo.png"
social:
  name: "Metaphor: ReFantazio Offline Community"
  links:
    - "https://twitter.com/MetaphorOffline"
    - "https://github.com/Metaphor-ReFantazio-Offline"
    - "https://discord.gg/metaphor-refantazio-offline"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# SEO keywords
keywords: 
  - "metaphor refantazio offline"
  - "atlus jrpg offline tool"
  - "metaphor refantazio setup assistant"
  - "offline jrpg launcher"
  - "persona team game offline"
  - "metaphor refantazio no internet"
  - "jrpg offline mode"
  - "atlus game configuration"
  - "metaphor controller setup"
  - "offline rpg tool"
  - "fantasy jrpg assistant"

# Navigation
header_pages:
  - setup.md
  - quickstart.md
  - troubleshooting.md
  - faq.md
  - community.md

# Gaming-specific configuration
gaming:
  platforms:
    - name: "Steam"
      icon: "steam"
      supported: true
    - name: "Epic Games Store"
      icon: "epic"
      supported: true
    - name: "Microsoft Store"
      icon: "microsoft"
      supported: true
    - name: "GOG"
      icon: "gog"
      supported: true
  
  controllers:
    - name: "Xbox Controllers"
      compatibility: "Full"
      features: ["Vibration", "All Buttons", "Wireless"]
    - name: "PlayStation Controllers"
      compatibility: "Full"
      features: ["Vibration", "Adaptive Triggers", "Wireless"]
    - name: "Nintendo Controllers"
      compatibility: "Full"
      features: ["Pro Controller", "Joy-Cons", "Wireless"]

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - .internal/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/ 